stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  container_image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

default:
  before_script:
    - |
      major_version=$(echo $CI_COMMIT_REF_SLUG | cut -d. -f1)


build:build:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: build
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login $DOCKER_REGISTRY --username $DOCKER_REGISTRY_USER --password-stdin
  script:
    - docker build -t $container_image .
    - docker push $container_image